# Change these first
owner: kalolina # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
user-agent: koj-co
sites:
  - name: Kalolina LLC
    url: https://kalolina.com
  - name: Kalolina Hub
    url: https://hub.kalolina.com
  - name: Kalolina Email
    url: https://pro.kalolina.com
  - name: Kalolina SSO
    url: https://sso.kalolina.com  
  - name: Kalolina Status Page
    url: https://status.kalolina.com 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://hub.kalolina.com/uploads/company/63d12bba56ef7cbe30e43a03f999f016.png
  name: Kalolina Uptime
  introTitle: "**Kalolina LLC Status Page** monitors website availability and response times."
  introMessage: Additional information can be found at [Kalolina Hub](https://hub.kalolina.com)
  navbar:
    - title: Status
      href: https://kalolina.github.io/uptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
